// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GameMessageProto.proto
// Protobuf Java Version: 4.29.1

package org.herostory.protobuf.bean;

public final class GameMessageProto {
  private GameMessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GameMessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.herostory.protobuf.GameMsgId}
   */
  public enum GameMsgId
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>USER_LOGIN_CMD = 0;</code>
     */
    USER_LOGIN_CMD(0),
    /**
     * <code>USER_LOGIN_RESULT = 1;</code>
     */
    USER_LOGIN_RESULT(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        GameMsgId.class.getName());
    }
    /**
     * <code>USER_LOGIN_CMD = 0;</code>
     */
    public static final int USER_LOGIN_CMD_VALUE = 0;
    /**
     * <code>USER_LOGIN_RESULT = 1;</code>
     */
    public static final int USER_LOGIN_RESULT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static GameMsgId valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static GameMsgId forNumber(int value) {
      switch (value) {
        case 0: return USER_LOGIN_CMD;
        case 1: return USER_LOGIN_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameMsgId>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        GameMsgId> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameMsgId>() {
            public GameMsgId findValueByNumber(int number) {
              return GameMsgId.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.herostory.protobuf.bean.GameMessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameMsgId[] VALUES = values();

    public static GameMsgId valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private GameMsgId(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.herostory.protobuf.GameMsgId)
  }

  public interface UserLoginCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.herostory.protobuf.UserLoginCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 2;</code>
     * @return The heroAvatar.
     */
    java.lang.String getHeroAvatar();
    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 2;</code>
     * @return The bytes for heroAvatar.
     */
    com.google.protobuf.ByteString
        getHeroAvatarBytes();
  }
  /**
   * Protobuf type {@code org.herostory.protobuf.UserLoginCmd}
   */
  public static final class UserLoginCmd extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.herostory.protobuf.UserLoginCmd)
      UserLoginCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        UserLoginCmd.class.getName());
    }
    // Use UserLoginCmd.newBuilder() to construct.
    private UserLoginCmd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserLoginCmd() {
      heroAvatar_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.herostory.protobuf.bean.GameMessageProto.internal_static_org_herostory_protobuf_UserLoginCmd_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.herostory.protobuf.bean.GameMessageProto.internal_static_org_herostory_protobuf_UserLoginCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd.class, org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_ = 0;
    /**
     * <pre>
     * 用户id
     * </pre>
     *
     * <code>uint32 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int HEROAVATAR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object heroAvatar_ = "";
    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 2;</code>
     * @return The heroAvatar.
     */
    @java.lang.Override
    public java.lang.String getHeroAvatar() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        heroAvatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 英雄形象
     * </pre>
     *
     * <code>string heroAvatar = 2;</code>
     * @return The bytes for heroAvatar.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeroAvatarBytes() {
      java.lang.Object ref = heroAvatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heroAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeUInt32(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(heroAvatar_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, heroAvatar_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(heroAvatar_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, heroAvatar_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd)) {
        return super.equals(obj);
      }
      org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd other = (org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getHeroAvatar()
          .equals(other.getHeroAvatar())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + HEROAVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getHeroAvatar().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.herostory.protobuf.UserLoginCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.herostory.protobuf.UserLoginCmd)
        org.herostory.protobuf.bean.GameMessageProto.UserLoginCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.herostory.protobuf.bean.GameMessageProto.internal_static_org_herostory_protobuf_UserLoginCmd_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.herostory.protobuf.bean.GameMessageProto.internal_static_org_herostory_protobuf_UserLoginCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd.class, org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd.Builder.class);
      }

      // Construct using org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0;
        heroAvatar_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.herostory.protobuf.bean.GameMessageProto.internal_static_org_herostory_protobuf_UserLoginCmd_descriptor;
      }

      @java.lang.Override
      public org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd getDefaultInstanceForType() {
        return org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd.getDefaultInstance();
      }

      @java.lang.Override
      public org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd build() {
        org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd buildPartial() {
        org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd result = new org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.heroAvatar_ = heroAvatar_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd) {
          return mergeFrom((org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd other) {
        if (other == org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (!other.getHeroAvatar().isEmpty()) {
          heroAvatar_ = other.heroAvatar_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                heroAvatar_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <pre>
       * 用户id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 用户id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户id
       * </pre>
       *
       * <code>uint32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object heroAvatar_ = "";
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 2;</code>
       * @return The heroAvatar.
       */
      public java.lang.String getHeroAvatar() {
        java.lang.Object ref = heroAvatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          heroAvatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 2;</code>
       * @return The bytes for heroAvatar.
       */
      public com.google.protobuf.ByteString
          getHeroAvatarBytes() {
        java.lang.Object ref = heroAvatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heroAvatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 2;</code>
       * @param value The heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatar(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        heroAvatar_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeroAvatar() {
        heroAvatar_ = getDefaultInstance().getHeroAvatar();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 英雄形象
       * </pre>
       *
       * <code>string heroAvatar = 2;</code>
       * @param value The bytes for heroAvatar to set.
       * @return This builder for chaining.
       */
      public Builder setHeroAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        heroAvatar_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.herostory.protobuf.UserLoginCmd)
    }

    // @@protoc_insertion_point(class_scope:org.herostory.protobuf.UserLoginCmd)
    private static final org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd();
    }

    public static org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserLoginCmd>
        PARSER = new com.google.protobuf.AbstractParser<UserLoginCmd>() {
      @java.lang.Override
      public UserLoginCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserLoginCmd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserLoginCmd> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.herostory.protobuf.bean.GameMessageProto.UserLoginCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_herostory_protobuf_UserLoginCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_herostory_protobuf_UserLoginCmd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026GameMessageProto.proto\022\026org.herostory." +
      "protobuf\"2\n\014UserLoginCmd\022\016\n\006userId\030\001 \001(\r" +
      "\022\022\n\nheroAvatar\030\002 \001(\t*6\n\tGameMsgId\022\022\n\016USE" +
      "R_LOGIN_CMD\020\000\022\025\n\021USER_LOGIN_RESULT\020\001B\035\n\033" +
      "org.herostory.protobuf.beanb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_herostory_protobuf_UserLoginCmd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_herostory_protobuf_UserLoginCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_herostory_protobuf_UserLoginCmd_descriptor,
        new java.lang.String[] { "UserId", "HeroAvatar", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
